import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Clerk",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton showName />
            </SignedIn>
          </header>
          <main className="w-full h-screen flex justify-center items-center">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
