import {
  ClerkProvider,
  GoogleOneTap,
  SignInButton,
  SignInWithMetamaskButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import "./globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Clerk",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <header>
            <SignedOut>
              <SignInButton>
                <button className="p-1 border border-green-200 rounded-md">
                  Sign in
                </button>
              </SignInButton>
            </SignedOut>

            <SignedIn>
              <UserButton
                showName
                appearance={{
                  elements: {
                    userButtonBox: "bg-green-200 border border-2 rounded-md",
                  },
                }}
              />
            </SignedIn>
          </header>
          <main className="w-full h-screen flex justify-center items-center">
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
